[general]
import = ["~/.config/alacritty/themes/catppuccin-macchiato.toml"]

[env]
XDG_CONFIG_HOME = "/Users/contassot/.config"

[font]
size = 14

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "~"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 37
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = '\'
key = 47
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = "["
key = "("
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = "{"
key = "("
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = ")"
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = "}"
key = ")"
mods = "Alt"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/opt/homebrew/bin/nu"

[window]
blur = false
decorations = "Buttonless"
opacity = 1.0
option_as_alt = "Both"
