[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[font]
size = 14

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetbrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "~"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 37
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = '\'
key = 47
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = "["
key = "("
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = "{"
key = "("
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = ")"
mods = "Alt | Shift"

[[keyboard.bindings]]
chars = "}"
key = ")"
mods = "Alt"

[[keyboard.bindings]]
chars = "¼"
key = "h"
mods = "Command"

[[keyboard.bindings]]
chars = "½"
key = "-"
mods = "Command"

[[keyboard.bindings]]
chars = "¾"
key = "="
mods = "Command"

[[keyboard.bindings]]
chars = ""
key = "m"
mods = "Command"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/opt/homebrew/bin/nu"

[window]
blur = false
decorations = "Buttonless"
opacity = 1.0
option_as_alt = "Both"
