after-startup-command = [
    'exec-and-forget sketchybar',
    'exec-and-forget borders active_color=0xffc6a0f6 inactive_color=0x00000000 width=7.0'
]

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    'sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]
start-at-login = false
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.top = [{ monitor."Built-in" = 10 }, 40]
outer.left = 10
outer.bottom = 10
outer.right = 10

[mode.main.binding]
cmd-alt-ctrl-f2= 'exec-and-forget ~/.config/aerospace/keyboard-brightness +0.1'
cmd-alt-ctrl-f1 = 'exec-and-forget ~/.config/aerospace/keyboard-brightness -0.1'

cmd-alt-ctrl-slash = 'layout tiles horizontal vertical'
cmd-alt-ctrl-comma = 'layout accordion horizontal vertical'

cmd-alt-ctrl-h = 'focus left'
cmd-alt-ctrl-left = 'focus left'
cmd-alt-ctrl-j = 'focus down'
cmd-alt-ctrl-down = 'focus down'
cmd-alt-ctrl-k = 'focus up'
cmd-alt-ctrl-up = 'focus up'
cmd-alt-ctrl-l = 'focus right'
cmd-alt-ctrl-right = 'focus right'

cmd-alt-ctrl-shift-h = 'move left'
cmd-alt-ctrl-shift-left = 'move left'
cmd-alt-ctrl-shift-j = 'move down'
cmd-alt-ctrl-shift-down = 'move down'
cmd-alt-ctrl-shift-k = 'move up'
cmd-alt-ctrl-shift-up = 'move up'
cmd-alt-ctrl-shift-l = 'move right'
cmd-alt-ctrl-shift-right = 'move right'

cmd-alt-ctrl-1 = 'focus-monitor 1'
cmd-alt-ctrl-2 = 'focus-monitor 2'
cmd-alt-ctrl-3 = 'focus-monitor 3'
cmd-alt-ctrl-4 = 'focus-monitor 4'
cmd-alt-ctrl-5 = 'focus-monitor 5'
cmd-alt-ctrl-6 = 'focus-monitor 6'
cmd-alt-ctrl-7 = 'focus-monitor 7'
cmd-alt-ctrl-8 = 'focus-monitor 8'
cmd-alt-ctrl-9 = 'focus-monitor 9'
cmd-alt-ctrl-a = 'workspace A' # In your config, you can drop workspace bindings that you don't need
cmd-alt-ctrl-b = 'workspace B'
cmd-alt-ctrl-c = 'workspace C'
cmd-alt-ctrl-d = 'workspace D'
cmd-alt-ctrl-e = 'workspace E'
cmd-alt-ctrl-f = 'workspace F'
cmd-alt-ctrl-g = 'workspace G'
cmd-alt-ctrl-i = 'workspace I'
cmd-alt-ctrl-m = 'workspace M'
cmd-alt-ctrl-n = 'workspace N'
cmd-alt-ctrl-o = 'workspace O'
cmd-alt-ctrl-p = 'workspace P'
cmd-alt-ctrl-q = 'workspace Q'
cmd-alt-ctrl-s = 'workspace S'
cmd-alt-ctrl-t = 'workspace T'
cmd-alt-ctrl-u = 'workspace U'
cmd-alt-ctrl-v = 'workspace V'
cmd-alt-ctrl-w = 'workspace W'
cmd-alt-ctrl-x = 'workspace X'
cmd-alt-ctrl-y = 'workspace Y'
cmd-alt-ctrl-z = 'workspace Z'

cmd-alt-ctrl-shift-1 = [
    'move-workspace-to-monitor 1',
    'focus-monitor 1',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-2 = [
    'move-workspace-to-monitor 2',
    'focus-monitor 2',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-3 = [
    'move-workspace-to-monitor 3',
    'focus-monitor 3',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-4 = [
    'move-workspace-to-monitor 4',
    'focus-monitor 4',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-5 = [
    'move-workspace-to-monitor 5',
    'focus-monitor 5',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-6 = [
    'move-workspace-to-monitor 6',
    'focus-monitor 6',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-7 = [
    'move-workspace-to-monitor 7',
    'focus-monitor 7',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-8 = [
    'move-workspace-to-monitor 8',
    'focus-monitor 8',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]
cmd-alt-ctrl-shift-9 = [
    'move-workspace-to-monitor 9',
    'focus-monitor 9',
    'exec-and-forget sketchybar --trigger aerospace_monitor_change'
]

cmd-alt-ctrl-shift-a = ['move-node-to-workspace A', 'workspace A' ]
cmd-alt-ctrl-shift-b = ['move-node-to-workspace B', 'workspace B' ]
cmd-alt-ctrl-shift-c = ['move-node-to-workspace C', 'workspace C' ]
cmd-alt-ctrl-shift-d = ['move-node-to-workspace D', 'workspace D' ]
cmd-alt-ctrl-shift-e = ['move-node-to-workspace E', 'workspace E' ]
cmd-alt-ctrl-shift-f = ['move-node-to-workspace F', 'workspace F' ]
cmd-alt-ctrl-shift-g = ['move-node-to-workspace G', 'workspace G' ]
cmd-alt-ctrl-shift-i = ['move-node-to-workspace I', 'workspace I' ]
cmd-alt-ctrl-shift-m = ['move-node-to-workspace M', 'workspace M' ]
cmd-alt-ctrl-shift-n = ['move-node-to-workspace N', 'workspace N' ]
cmd-alt-ctrl-shift-o = ['move-node-to-workspace O', 'workspace O' ]
cmd-alt-ctrl-shift-p = ['move-node-to-workspace P', 'workspace P' ]
cmd-alt-ctrl-shift-q = ['move-node-to-workspace Q', 'workspace Q' ]
cmd-alt-ctrl-shift-s = ['move-node-to-workspace S', 'workspace S' ]
cmd-alt-ctrl-shift-t = ['move-node-to-workspace T', 'workspace T' ]
cmd-alt-ctrl-shift-u = ['move-node-to-workspace U', 'workspace U' ]
cmd-alt-ctrl-shift-v = ['move-node-to-workspace V', 'workspace V' ]
cmd-alt-ctrl-shift-w = ['move-node-to-workspace W', 'workspace W' ]
cmd-alt-ctrl-shift-x = ['move-node-to-workspace X', 'workspace X' ]
cmd-alt-ctrl-shift-y = ['move-node-to-workspace Y', 'workspace Y' ]
cmd-alt-ctrl-shift-z = ['move-node-to-workspace Z', 'workspace Z' ]

cmd-alt-ctrl-tab = 'workspace-back-and-forth'

cmd-alt-ctrl-shift-semicolon = ['mode service', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=service'] 
cmd-alt-ctrl-shift-r = ['mode resize', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=resize']


[mode.service.binding]
esc = ['reload-config', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']
r = ['flatten-workspace-tree', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main'] # reset layout
f = ['layout floating tiling', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']

cmd-alt-ctrl-shift-h = ['join-with left', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']
cmd-alt-ctrl-shift-j = ['join-with down', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']
cmd-alt-ctrl-shift-k = ['join-with up', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']
cmd-alt-ctrl-shift-l = ['join-with right', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']

equal='enable toggle'
down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']


[mode.resize.binding]
minus = 'resize smart -50'
equal = 'resize smart +50'
shift-minus = 'resize smart -10'
shift-equal = 'resize smart +10'
r = ['balance-sizes', 'mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']
esc = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']
enter = ['mode main', 'exec-and-forget sketchybar --trigger aerospace_mode_change AEROSPACE_MODE=main']


[key-mapping.key-notation-to-key-code]
    '&' = '1'
    'é' = '2'
    '"' = '3'
    "'" = '4'
    '(' = '5'
    '§' = '6'
    'è' = '7'
    '!' = '8'
    'ç' = '9'
    'à' = '0'
    ')' = 'minus'
    'minus' = 'equal'

    a = 'q'
    z = 'w'
    e = 'e'
    r = 'r'
    t = 't'
    y = 'y'
    u = 'u'
    i = 'i'
    o = 'o'
    p = 'p'
    '^' = 'leftSquareBracket'
    '$' = 'rightSquareBracket'

    q = 'a'
    s = 's'
    d = 'd'
    f = 'f'
    g = 'g'
    h = 'h'
    j = 'j'
    k = 'k'
    l = 'l'
    m = 'semicolon'
    'ù' = 'quote'

    w = 'z'
    x = 'x'
    c = 'c'
    v = 'v'
    b = 'b'
    n = 'n'
    comma = 'm'
    semicolon = 'comma'
    colon = 'period'
    equal = 'slash'

[[on-window-detected]]
    if.app-id = 'org.chromium.Chromium'
    run = 'move-node-to-workspace E' # mnemonics E - E2E

[[on-window-detected]]
    if.app-id = 'com.1password.1password'
    run = 'layout floating'
