theme = "catppuccin_macchiato_bgt"

[editor]
shell = ["nu", "--stdin", "-c"]

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true

[keys.normal]
S-C-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
S-C-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-y = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
# D = "@xd"

[keys.normal."space"."m"]
1 = ":pipe str downcase"
2 = ":pipe str snake-case"
3 = ":pipe str screaming-snake-case"
4 = ":pipe str camel-case"
5 = ":pipe str kebab-case"
6 = ":pipe str pascal-case"
7 = ":pipe str title-case"
8 = ":pipe str upcase"

# [keys.normal."space"."o"]
# n = ":o <C-r>%<C-w>"
# x = ":sh rm <C-r>%"
