export def 'from name' [] {
  match $in {
   "Lie" => { ":ableton:" }
   "Activity Monitor" => { ":activity_monitor:" }
   "Adobe Bridge" => { ":adobe_bridge:" }
   "Affinity Designer" => { ":affinity_designer:" }
   "Affinity Designer 2" => { ":affinity_designer_2:" }
   "Affinity Photo" => { ":affinity_photo:" }
   "Affinity Photo 2" => { ":affinity_photo_2:" }
   "Affinity Publisher" => { ":affinity_publisher:" }
   "Affinity Publisher 2" => { ":affinity_publisher_2:" }
   "Airmail" => { ":airmail:" }
   "Alacritty" => { ":alacritty:" }
   "Alfred" => { ":alfred:" }
   "Android Messages" => { ":android_messages:" }
   "Android Studio" => { ":android_studio:" }
   "Anki" => { ":anki:" }
   "Anytype" => { ":anytype:" }
   "App Eraser" => { ":app_eraser:" }
   "App Store" => { ":app_store:" }
   "Arc" => { ":arc:" }
   "Arduino" | "Arduino IDE" => { ":arduino:" }
   "Atom" => { ":atom:" }
   "Audacity" => { ":audacity:" }
   "Bambu Studio" => { ":bambu_studio:" }
   "MoneyMoney" => { ":bank:" }
   "Battle.net" => { ":battle_net:" }
   "Bear" => { ":bear:" }
   "BetterTouchTool" => { ":bettertouchtool:" }
   "Bilibili" | "哔哩哔哩" => { ":bilibili:" }
   "Bitwarden" => { ":bit_warden:" }
   "Blender" => { ":blender:" }
   "BluOS Controller" => { ":bluos_controller:" }
   "Calibre" => { ":book:" }
   "Brave Browser" => { ":brave_browser:" }
   "Bruno" => { ":bruno:" }
   "BusyCal" => { ":busycal:" }
   "Calculator" | "Calculette" => { ":calculator:" }
   "Calendar" | "日历" | "Fantastical" | "Cron" | "Amie" | "Calendrier" | "カレンダー" | "Notion Calendar" => { ":calendar:" }
   "calibre" => { ":calibre:" }
   "Caprine" => { ":caprine:" }
   "Amazon Chime" => { ":chime:" }
   "Citrix Workspace" | "Citrix Viewer" => { ":citrix:" }
   "Claude" => { ":claude:" }
   "ClickUp" => { ":click_up:" }
   "Code" | "Code - Insiders" => { ":code:" }
   "Cold Turkey Blocker" => { ":cold_turkey_blocker:" }
   "Color Picker" | "数码测色计" => { ":color_picker:" }
   "Copilot" => { ":copilot:" }
   "CotEditor" => { ":coteditor:" }
   "Creative Cloud" => { ":creative_cloud:" }
   "Cursor" => { ":cursor:" }
   "Cypress" => { ":cypress:" }
   "DataGrip" => { ":datagrip:" }
   "DataSpell" => { ":dataspell:" }
   "DaVinci Resolve" => { ":davinciresolve:" }
   "DBeaver" => { ":dbeaver:" }
   "Deezer" => { ":deezer:" }
   "Default" => { ":default:" }
   "CleanMyMac X" => { ":desktop:" }
   "DEVONthink 3" => { ":devonthink3:" }
   "DingTalk" | "钉钉" | "阿里钉" => { ":dingtalk:" }
   "Discord" | "Discord Canary" | "Discord PTB" => { ":discord:" }
   "Docker" | "Docker Desktop" => { ":docker:" }
   "GrandTotal" | "Receipts" => { ":dollar:" }
   "Double Commander" => { ":doublecmd:" }
   "Drafts" => { ":drafts:" }
   "draw.io" => { ":draw_io:" }
   "Dropbox" => { ":dropbox:" }
   "Element" => { ":element:" }
   "Emacs" => { ":emacs:" }
   "Evernote Legacy" => { ":evernote_legacy:" }
   "FaceTime" | "FaceTime 通话" => { ":face_time:" }
   "Figma" => { ":figma:" }
   "Final Cut Pro" => { ":final_cut_pro:" }
   "Finder" | "访达" => { ":finder:" }
   "Firefox" => { ":firefox:" }
   "Firefox Developer Edition" | "Firefox Nightly" => { ":firefox_developer_edition:" }
   "Folx" => { ":folx:" }
   "Fork" => { ":fork:" }
   "Freeform" => { ":freeform:" }
   "FreeTube" => { ":freetube:" }
   "Fusion" => { ":fusion:" }
   "System Preferences" | "System Settings" | "系统设置" | "Réglages Système" | "システム設定" => { ":gear:" }
   "Ghostty" => { ":ghostty:" }
   "GitHub Desktop" => { ":git_hub:" }
   "Godot" => { ":godot:" }
   "GoLand" => { ":goland:" }
   "Chromium" | "Google Chrome" | "Google Chrome Canary" => { ":google_chrome:" }
   "Grammarly Editor" => { ":grammarly:" }
   "Home Assistant" => { ":home_assistant:" }
   "Hyper" => { ":hyper:" }
   "IntelliJ IDEA" => { ":idea:" }
   "IINA" => { ":iina:" }
   "Adobe Illustrator" | "Illustrator" => { ":illustrator:" }
   "Adobe InDesign" | "InDesign" => { ":indesign:" }
   "Infuse" => { ":infuse:" }
   "Inkdrop" => { ":inkdrop:" }
   "Inkscape" => { ":inkscape:" }
   "Insomnia" => { ":insomnia:" }
   "iPhone Mirroring" => { ":iphone_mirroring:" }
   "Iris" => { ":iris:" }
   "iTerm" | "iTerm2" => { ":iterm:" }
   "Jellyfin Media Player" => { ":jellyfin:" }
   "Joplin" => { ":joplin:" }
   "카카오톡" | "KakaoTalk" => { ":kakaotalk:" }
   "Kakoune" => { ":kakoune:" }
   "KeePassXC" => { ":kee_pass_x_c:" }
   "Keyboard Maestro" => { ":keyboard_maestro:" }
   "Keynote" | "Keynote 讲演" => { ":keynote:" }
   "kitty" => { ":kitty:" }
   "Kodi" => { ":kodi:" }
   "LanguageTool for Desktop" => { ":languagetool_for_desktop:" }
   "League of Legends" => { ":league_of_legends:" }
   "LibreWolf" => { ":libre_wolf:" }
   "Adobe Lightroom" => { ":lightroom:" }
   "Lightroom Classic" => { ":lightroomclassic:" }
   "LINE" => { ":line:" }
   "Linear" => { ":linear:" }
   "LM Studio" => { ":lm_studio:" }
   "LocalSend" => { ":localsend:" }
   "Logic Pro" => { ":logicpro:" }
   "Logseq" => { ":logseq:" }
   "Canary Mail" | "HEY" | "Mail" | "Mailspring" | "MailMate" | "Superhuman" | "Spark" | "邮件" | "メール" => { ":mail:" }
   "MAMP" | "MAMP PRO" => { ":mamp:" }
   "Maps" | "Google Maps" | "マップ" => { ":maps:" }
   "Marta" => { ":marta:" }
   "Matlab" => { ":matlab:" }
   "Mattermost" => { ":mattermost:" }
   "Messages" | "信息" | "Nachrichten" | "メッセージ" => { ":messages:" }
   "Messenger" => { ":messenger:" }
   "Microsoft Edge" => { ":microsoft_edge:" }
   "Microsoft Excel" => { ":microsoft_excel:" }
   "Microsoft Outlook" => { ":microsoft_outlook:" }
   "Microsoft PowerPoint" => { ":microsoft_power_point:" }
   "Microsoft Remote Desktop" => { ":microsoft_remote_desktop:" }
   "Microsoft Teams" | "Microsoft Teams (work or school)" => { ":microsoft_teams:" }
   "Microsoft Word" => { ":microsoft_word:" }
   "Min" => { ":min_browser:" }
   "Miro" => { ":miro:" }
   "MongoDB Compass" => { ":mongodb:" }
   "Moonlight" => { ":moonlight:" }
   "mpv" => { ":mpv:" }
   "Mullvad Browser" => { ":mullvad_browser:" }
   "Music" | "音乐" | "Musique" | "ミュージック" => { ":music:" }
   "Neovide" | "neovide" => { ":neovide:" }
   "Neovim" | "neovim" | "nvim" => { ":neovim:" }
   "网易云音乐" => { ":netease_music:" }
   "Noodl" | "Noodl Editor" => { ":noodl:" }
   "NordVPN" => { ":nord_vpn:" }
   "Notability" => { ":notability:" }
   "Notes" | "备忘录" | "メモ" => { ":notes:" }
   "Notion" => { ":notion:" }
   "Nova" => { ":nova:" }
   "Numbers" | "Numbers 表格" => { ":numbers:" }
   "Obsidian" => { ":obsidian:" }
   "OBS" => { ":obsstudio:" }
   "OmniFocus" => { ":omni_focus:" }
   "1Password" => { ":one_password:" }
   "Open Video Downloader" => { ":open_video_downloader:" }
   "ChatGPT" => { ":openai:" }
   "OpenAI Translator" => { ":openai_translator:" }
   "OpenVPN Connect" => { ":openvpn_connect:" }
   "Opera" => { ":opera:" }
   "OrbStack" => { ":orbstack:" }
   "OrcaSlicer" => { ":orcaslicer:" }
   "Orion" | "Orion RC" => { ":orion:" }
   "Pages" | "Pages 文稿" => { ":pages:" }
   "Parallels Desktop" => { ":parallels:" }
   "Parsec" => { ":parsec:" }
   "Passwords" => { ":passwords:" }
   "Preview" | "预览" | "Skim" | "zathura" | "Aperçu" | "プレビュー" => { ":pdf:" }
   "PDF Expert" => { ":pdf_expert:" }
   "Pearcleaner" => { ":pearcleaner:" }
   "Phoenix Slides" => { ":phoenix_slides:" }
   "Photos" => { ":photos:" }
   "Adobe Photoshop" => { ":photoshop:" }
   "PhpStorm" => { ":php_storm:" }
   "Pi-hole Remote" => { ":pihole:" }
   "Pine" => { ":pine:" }
   "Plex" => { ":plex:" }
   "Plexamp" => { ":plexamp:" }
   "Podcasts" | "播客" => { ":podcasts:" }
   "PomoDone App" => { ":pomodone:" }
   "Postman" => { ":postman:" }
   "Proton Mail" | "Proton Mail Bridge" => { ":proton_mail:" }
   "Proton VPN" | "ProtonVPN" => { ":proton_vpn:" }
   "PrusaSlicer" | "SuperSlicer" => { ":prusaslicer:" }
   "PyCharm" => { ":pycharm:" }
   "QQ" => { ":qq:" }
   "QQ音乐" | "QQMusic" => { ":qqmusic:" }
   "Quantumult X" => { ":quantumult_x:" }
   "qutebrowser" => { ":qute_browser:" }
   "Raindrop.io" => { ":raindrop_io:" }
   "Reeder" => { ":reeder5:" }
   "Reminders" | "提醒事项" | "Rappels" | "リマインダー" => { ":reminders:" }
   "Replit" => { ":replit:" }
   "Repo Prompt" => { ":repo_prompt:" }
   "Rider" | "JetBrains Rider" => { ":rider:" }
   "Rio" => { ":rio:" }
   "Royal TSX" => { ":royaltsx:" }
   "RustDesk" => { ":rustdesk:" }
   "Safari" | "Safari浏览器" | "Safari Technology Preview" => { ":safari:" }
   "Sequel Ace" => { ":sequel_ace:" }
   "Sequel Pro" => { ":sequel_pro:" }
   "Session" => { ":session:" }
   "Setapp" => { ":setapp:" }
   "SF Symbols" => { ":sf_symbols:" }
   "Signal" => { ":signal:" }
   "sioyek" => { ":sioyek:" }
   "Sketch" => { ":sketch:" }
   "Skype" => { ":skype:" }
   "Slack" => { ":slack:" }
   "Spark Desktop" => { ":spark:" }
   "Spotify" => { ":spotify:" }
   "Spotlight" => { ":spotlight:" }
   "Studio 3T" => { ":studio_3t:" }
   "Sublime Text" => { ":sublime_text:" }
   "superProductivity" => { ":superproductivity:" }
   "Surfshark" => { ":surfshark:" }
   "Tabby" => { ":tabby:" }
   "TablePlus" => { ":tableplus:" }
   "Tana" => { ":tana:" }
   "TeamSpeak 3" => { ":team_speak:" }
   "Telegram" => { ":telegram:" }
   "Terminal" | "终端" | "ターミナル" => { ":terminal:" }
   "Typora" => { ":text:" }
   "TextEdit" => { ":textedit:" }
   "Microsoft To Do" | "Things" => { ":things:" }
   "Thunderbird" => { ":thunderbird:" }
   "TickTick" => { ":tick_tick:" }
   "TIDAL" => { ":tidal:" }
   "Tiny RDM" => { ":tinyrdm:" }
   "Todoist" => { ":todoist:" }
   "Toggl Track" => { ":toggl_track:" }
   "Tor Browser" => { ":tor_browser:" }
   "Tower" => { ":tower:" }
   "Transmit" => { ":transmit:" }
   "Trello" => { ":trello:" }
   "Tweetbot" | "Twitter" => { ":twitter:" }
   "UTM" => { ":utm:" }
   "MacVim" | "Vim" | "VimR" => { ":vim:" }
   "Vivaldi" => { ":vivaldi:" }
   "VLC" => { ":vlc:" }
   "VMware Fusion" => { ":vmware_fusion:" }
   "VSCodium" => { ":vscodium:" }
   "Warp" => { ":warp:" }
   "Weather" => { ":weather:" }
   "WebStorm" => { ":web_storm:" }
   "Webull Desktop" => { ":webull:" }
   "微信" | "WeChat" => { ":wechat:" }
   "企业微信" | "WeCom" => { ":wecom:" }
   "WezTerm" => { ":wezterm:" }
   "WhatsApp" | "‎WhatsApp" => { ":whats_app:" }
   "Xcode" => { ":xcode:" }
   "Yandex Browser"  | "Yandex Browser" | "Yandex" => { ":yandex_bower:" }
   "Yandex Music" => { ":yandex_music:" }
   "Yuque" | "语雀" => { ":yuque:" }
   "Zed" => { ":zed:" }
   "Zen Browser" | "Zen" => { ":zen_browser:" }
   "Zeplin" => { ":zeplin:" }
   "zoom.us" => { ":zoom:" }
   "Zotero" => { ":zotero:" }
   "Zulip" => { ":zulip:" }
   _ => { ":default:" }
  }
}
